name: Fix JS and Vue code style issues

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string

      package-manager:
        default: "yarn"
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  eslint:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    runs-on: self-hosted

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node
        if: ${{ !env.fontawesome-secret }}
        env:
          fontawesome-secret: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Setup Node with Font Awesome registry
        if: ${{ env.fontawesome-secret }}
        env:
          fontawesome-secret: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: "https://npm.fontawesome.com/"

      - name: Authenticate private node registries
        run: |
          if [[ -n "${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}" ]]; then
            echo "setting npm token to ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}"
            npm config set '//npm.fontawesome.com/:_authToken' "${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}"
          else
            echo "FONTAWESOME_NPM_AUTH_TOKEN not set, removing it"
            npm config delete '//npm.fontawesome.com/:_authToken'
          fi

      - name: Get yarn cache directory path
        if: ${{ inputs.package-manager == 'yarn' }}
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v3
        if: ${{ inputs.package-manager == 'yarn' }}
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-${{ inputs.node-version }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ inputs.node-version }}-yarn

      - name: Install node dependencies using yarn
        if: ${{ inputs.package-manager == 'yarn' }}
        run: |
          yarn install --pure-lockfile

      - name: Install pnpm
        if: ${{ inputs.package-manager == 'pnpm' }}
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        if: ${{ inputs.package-manager == 'pnpm' }}
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        if: ${{ inputs.package-manager == 'pnpm' }}
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install node dependencies using pnpm
        if: ${{ inputs.package-manager == 'pnpm' }}
        run: |
          pnpm install

      - name: Run ESLint
        run: |
          npm run lint:fix

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: |
            Fix styling 💄

            [ci skip]

